esphome:
  name: "${name}"
  name_add_mac_suffix: true

project:
    name: raspiaudio.mn-cast.esphome
    version: "1.0"

dashboard_import:
  package_import_url: https://github.com/RASPIAUDIO/raspiaudio.github.io/blob/main/Mncast/Homeassistant/mn-cast.yaml
  import_full_config: false

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "password_is_musemuse"
    password: "musemuse"

media_player:
  - platform: i2s_audio
    id: media_out
    name: MnCast
    dac_type: external
    i2s_lrclk_pin: GPIO25
    i2s_dout_pin: GPIO26
    i2s_bclk_pin: GPIO5
    mode: stereo
    mute_pin:
      number: GPIO33
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: Button
    on_click:
      - media_player.toggle: media_out

light:
  - platform: fastled_clockless
    name: LED
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_b:
      number: GPIO32 
      mode: INPUT_PULLUP
    pin_a:
      number: GPIO19
      mode: INPUT_PULLUP
    on_clockwise:
      - media_player.volume_up  
      - logger.log: "Turned Clockwise"
    on_anticlockwise:
      - media_player.volume_down
      - logger.log: "Turned Anticlockwise"

i2c:
  sda: GPIO18
  scl: GPIO23

infrared:
  rx_pin: GPIO21

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 20

time:
  - platform: homeassistant
    id: esptime

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.strftime(0, 60, id(my_font), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());
